FROM node AS build 

WORKDIR /usr/src/app/

COPY package.json package-lock.json /usr/src/app/

RUN npm install 

RUN npm run build 

FROM nginx 

RUN rm -rf /etc/nginx/conf.d/default.conf 

COPY frontend.conf /etc/nginx/conf.d/frontend.conf

COPY --from=build /usr/src/app/build/ /usr/share/nginx/html/



