name: CD pipeline 
on: 
  workflow_dispatch:
    inputs:
      deploy_frontend:
        type: boolean
        description: to deploy frontend
        default: false
      deploy_backend:
        type: boolean
        description: to deploy backend
        default: false

jobs:
  deploy_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: findout which path changed 
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: | 
          frontend: 
            - "frontend/**"
          backend:
            - "backend/**"
    
    - name: deploy frontend
      if: github.event.inputs.deploy_frontend == 'true'
      run: | 
        echo "deploying code for frontend"
    
    - name: deploy backend
      if: github.event.inputs.deploy_backend == 'true'
      run: | 
        echo "deploying code for frontend"