name: CI pipeline 
on: 
  push:
    branches:
      - "main"

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    
    - name: first 10 in SHA
      id: tag
      run : | 
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: find out which path changed
      uses: dorny/paths-filter@v2
      id: filter 
      with: 
        filters: | 
          frontend: 
            - "frontend/**"
          backend:
            - "backend/**"
    
    - name: login to azure 
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: build and push frontend
      if: steps.filter.outputs.frontend == 'true'
      run: | 
        cd ./frontend
        docker build -t casinomernregistry.azurecr.io/frontend:${{steps.tag.outputs.sha}} -f Dockerfile.prod .
        docker push casinomernregistry.azurecr.io/frontend:${{steps.tag.outputs.sha }} -f Dockerfile.prod .
    
    - name: build and push backend
      if: steps.filter.outputs.backend == 'true'
      run: | 
        cd ./backend
        docker build -t casinomernregistry.azurecr.io/backend:${{ steps.tag.outputs.sha }} -f Dockerfile.prod .
        docker push casinomernregistry.azurecr.io/backend:${{steps.tag.outputs.sha}} 
